# Generated by Django 4.2.30 on 2026-04-26 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_quiz_alter_utilisateur_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=500)),
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('option_c', models.CharField(max_length=200)),
                ('difficulte', models.CharField(choices=[('Facile', 'Facile'), ('Moyenne', 'Moyenne'), ('Difficile', 'Difficile')], default='Facile', max_length=15)),
                ('reponse_correcte', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C')], max_length=1)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='utilisateurs.quiz')),
            ],
            options={
                'db_table': 'question',
            },
        ),
    ]
