# Generated by Django 4.2.30 on 2026-05-04 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_obtenu', models.IntegerField(default=0)),
                ('temps_ecoule', models.IntegerField(default=0)),
                ('date_passage', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives', to='utilisateurs.quiz')),
            ],
            options={
                'db_table': 'tentative',
            },
        ),
    ]
