# Generated by Django 4.2.30 on 2026-05-05 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_tentative'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('icone', models.CharField(default='bi-star-fill text-primary', max_length=255)),
                ('critere_obtention', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ObtentionBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_obtention', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.badge')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('etudiant', 'badge')},
            },
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='badges',
            field=models.ManyToManyField(blank=True, related_name='etudiants', through='utilisateurs.ObtentionBadge', to='utilisateurs.badge'),
        ),
    ]
